[package]
name = "agepy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "agepy"
crate-type = ["cdylib"]

[dependencies]
age = "0.11.1"
pyo3 = "0.23.3"
